@api = http://localhost:3000/clientes

###
POST {{api}}/register
Content-Type: application/json

{
    "NOMBRECLIENTE": "Prueba Prueba",
    "CIF": "34287923W",
    "DIRECCION1": "Una calle diferente",
    "CODPOSTAL": "03690",
    "POBLACION": "San Vicente del Raspeig",
    "PROVINCIA": "Alicante",
    "PAIS": "España",
    "TELEFONO1": "635262521",
    "E_MAIL": "emailPrueba@gmail.com",
    "USUARIO": "prueba4",
    "PASS": "contraseña",
    "NUMTARJETA":"1234123412341234",
    "TARCADUCIDAD": "0226", 
    "CVC": "333"
}


###
POST {{api}}/login
Content-Type: application/json

{
    "E_MAIL": "emailPrueba@gmail.com",
    "PASS": "contraseña"
}


###
POST {{api}}/login
Content-Type: application/json

{
    "t":"ZW1haWxQcnVlYmFAZ21haWwuY29tOnBydWViYTQ="
}

###
GET {{api}}/perfil/33029
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODA4ODAyMjl9.769UOM5P5Ty7AVD43GRm3bEsioCrlVsTQx6KxR0noVw'